name: build-java-quarkus

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Workflow build-java-quarkus configurado para implementação futura."
