name: deploy-dev

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Workflow deploy-dev configurado para implementação futura."
