name: validate-openapi

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Workflow validate-openapi configurado para implementação futura."
